/**
 * Campaign Definition Form (CRM-PAD Phase 6)
 *
 * 5-tab campaign form supporting create & edit modes:
 *   Tab 1: General — name, type, channel, dates, description, status
 *   Tab 2: Financial — budget, currency, advertisement cost, campaign cost
 *   Tab 3: Admin — lead list selector, campaign manager assignment
 *   Tab 4: Campaign Notes — email subject/body/signature, SMS content
 *   Tab 5: Brochure — multi-file upload with file list display
 *
 * Campaign code is auto-generated by the backend and displayed read-only.
 */

import { useState, useEffect, useCallback } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import {
  Card, CardContent, CardHeader, CardTitle,
} from '@ui/components/ui/card';
import { Button } from '@ui/components/ui/button';
import { Badge } from '@ui/components/ui/badge';
import { Input } from '@ui/components/ui/input';
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue,
} from '@ui/components/ui/select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@ui/components/ui/tabs';
import { toast } from 'sonner';
import {
  Megaphone, Save, Send, ArrowLeft, Upload, Trash2,
  FileText, Search, X,
} from 'lucide-react';

/* ---------- API helpers ---------- */

const API = '/api/v1/campaigns';

function getToken(): string {
  try {
    const stored = localStorage.getItem('trustoms-user');
    if (stored) {
      const parsed = JSON.parse(stored);
      return parsed.token || '';
    }
  } catch {
    // ignore
  }
  return '';
}

function authHeaders(): Record<string, string> {
  const token = getToken();
  const headers: Record<string, string> = { 'Content-Type': 'application/json' };
  if (token) headers['Authorization'] = `Bearer ${token}`;
  return headers;
}

function fetcher(url: string) {
  return fetch(url, { headers: authHeaders() }).then((r) => r.json());
}

/* ---------- Constants ---------- */

const CAMPAIGN_TYPES = [
  'PRODUCT_LAUNCH',
  'EVENT_INVITATION',
  'EDUCATIONAL',
  'REFERRAL',
  'CROSS_SELL',
  'UP_SELL',
  'RETENTION',
  'RE_ENGAGEMENT',
] as const;

const CHANNELS = ['EMAIL', 'SMS', 'MIXED'] as const;

const statusColors: Record<string, string> = {
  DRAFT: 'bg-gray-100 text-gray-800 dark:bg-gray-800 dark:text-gray-300',
  PENDING_APPROVAL: 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-300',
  APPROVED: 'bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-300',
  ACTIVE: 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-300',
  COMPLETED: 'bg-purple-100 text-purple-800 dark:bg-purple-900 dark:text-purple-300',
  CLOSED: 'bg-gray-100 text-gray-800 dark:bg-gray-800 dark:text-gray-300',
  REJECTED: 'bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-300',
};

/* ---------- Interfaces ---------- */

interface CampaignFormData {
  name: string;
  campaign_type: string;
  channel: string;
  start_date: string;
  end_date: string;
  description: string;
  budget_amount: string;
  budget_currency: string;
  advertisement_cost: string;
  campaign_cost: string;
  lead_list_id: string;
  campaign_manager_id: string;
  email_subject: string;
  email_body: string;
  email_signature: string;
  sms_content: string;
}

interface CampaignRecord {
  id: number;
  campaign_code: string;
  name: string;
  campaign_type: string;
  channel: string;
  status: string;
  description: string | null;
  start_date: string | null;
  end_date: string | null;
  budget_amount: string | null;
  budget_currency: string;
  advertisement_cost: string | null;
  campaign_cost: string | null;
  lead_list_id: number | null;
  campaign_manager_id: number | null;
  email_subject: string | null;
  email_body: string | null;
  email_signature: string | null;
  sms_content: string | null;
  created_at: string;
  updated_at: string;
}

interface LeadListOption {
  id: number;
  name: string;
  total_count: number;
  source_type: string;
}

interface BrochureFile {
  id: number;
  filename: string;
  size: number;
  uploaded_at: string;
}

const INITIAL_FORM: CampaignFormData = {
  name: '',
  campaign_type: '',
  channel: '',
  start_date: '',
  end_date: '',
  description: '',
  budget_amount: '',
  budget_currency: 'PHP',
  advertisement_cost: '',
  campaign_cost: '',
  lead_list_id: '',
  campaign_manager_id: '',
  email_subject: '',
  email_body: '',
  email_signature: '',
  sms_content: '',
};

/* ---------- Component ---------- */

export default function CampaignForm() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const isEdit = !!id;

  const [activeTab, setActiveTab] = useState('general');
  const [form, setForm] = useState<CampaignFormData>(INITIAL_FORM);
  const [leadListSearch, setLeadListSearch] = useState('');
  const [uploadFiles, setUploadFiles] = useState<File[]>([]);

  /* ---- Field updater ---- */

  const updateField = useCallback(
    <K extends keyof CampaignFormData>(field: K, value: CampaignFormData[K]) => {
      setForm((prev) => ({ ...prev, [field]: value }));
    },
    [],
  );

  /* ---- Queries ---- */

  const { data: existingCampaign, isPending: loadingCampaign } = useQuery<CampaignRecord>({
    queryKey: ['campaign-edit', id],
    queryFn: () => fetcher(`${API}/${id}`),
    enabled: isEdit,
  });

  const { data: leadListsData } = useQuery<{ data: LeadListOption[] }>({
    queryKey: ['lead-lists-select', leadListSearch],
    queryFn: () => fetcher(`/api/v1/lead-lists?search=${encodeURIComponent(leadListSearch)}&pageSize=50`),
  });

  const { data: brochuresData, isPending: brochuresLoading } = useQuery<{ data: BrochureFile[] }>({
    queryKey: ['campaign-brochures', id],
    queryFn: () => fetcher(`${API}/${id}/brochures`),
    enabled: isEdit,
  });

  const leadLists: LeadListOption[] = leadListsData?.data ?? [];
  const brochures: BrochureFile[] = brochuresData?.data ?? [];

  /* ---- Populate form on edit ---- */

  useEffect(() => {
    if (existingCampaign) {
      setForm({
        name: existingCampaign.name || '',
        campaign_type: existingCampaign.campaign_type || '',
        channel: existingCampaign.channel || '',
        start_date: existingCampaign.start_date?.split('T')[0] || '',
        end_date: existingCampaign.end_date?.split('T')[0] || '',
        description: existingCampaign.description || '',
        budget_amount: existingCampaign.budget_amount || '',
        budget_currency: existingCampaign.budget_currency || 'PHP',
        advertisement_cost: existingCampaign.advertisement_cost || '',
        campaign_cost: existingCampaign.campaign_cost || '',
        lead_list_id: existingCampaign.lead_list_id?.toString() || '',
        campaign_manager_id: existingCampaign.campaign_manager_id?.toString() || '',
        email_subject: existingCampaign.email_subject || '',
        email_body: existingCampaign.email_body || '',
        email_signature: existingCampaign.email_signature || '',
        sms_content: existingCampaign.sms_content || '',
      });
    }
  }, [existingCampaign]);

  /* ---- Mutations ---- */

  const saveMutation = useMutation({
    mutationFn: (payload: { data: CampaignFormData; asDraft: boolean }) => {
      const body = {
        name: payload.data.name,
        campaign_type: payload.data.campaign_type,
        channel: payload.data.channel || undefined,
        start_date: payload.data.start_date || undefined,
        end_date: payload.data.end_date || undefined,
        description: payload.data.description || undefined,
        budget_amount: payload.data.budget_amount ? parseFloat(payload.data.budget_amount) : undefined,
        budget_currency: payload.data.budget_currency,
        advertisement_cost: payload.data.advertisement_cost ? parseFloat(payload.data.advertisement_cost) : undefined,
        campaign_cost: payload.data.campaign_cost ? parseFloat(payload.data.campaign_cost) : undefined,
        lead_list_id: payload.data.lead_list_id ? parseInt(payload.data.lead_list_id, 10) : undefined,
        campaign_manager_id: payload.data.campaign_manager_id ? parseInt(payload.data.campaign_manager_id, 10) : undefined,
        email_subject: payload.data.email_subject || undefined,
        email_body: payload.data.email_body || undefined,
        email_signature: payload.data.email_signature || undefined,
        sms_content: payload.data.sms_content || undefined,
        status: payload.asDraft ? 'DRAFT' : undefined,
      };

      const url = isEdit ? `${API}/${id}` : API;
      const method = isEdit ? 'PUT' : 'POST';

      return fetch(url, {
        method,
        headers: authHeaders(),
        body: JSON.stringify(body),
      }).then((r) => {
        if (!r.ok) return r.json().then((e: { error?: string }) => { throw new Error(e.error || 'Save failed'); });
        return r.json();
      });
    },
    onSuccess: (_data: unknown, vars: { data: CampaignFormData; asDraft: boolean }) => {
      queryClient.invalidateQueries({ queryKey: ['campaign-list'] });
      queryClient.invalidateQueries({ queryKey: ['campaign-edit', id] });
      toast.success(vars.asDraft ? 'Campaign saved as draft' : 'Campaign submitted successfully');
      navigate('/crm/campaigns');
    },
    onError: (err: Error) => toast.error(err.message),
  });

  const uploadMutation = useMutation({
    mutationFn: (files: File[]) => {
      const formData = new FormData();
      files.forEach((file) => formData.append('brochures', file));

      const token = getToken();
      const headers: Record<string, string> = {};
      if (token) headers['Authorization'] = `Bearer ${token}`;

      return fetch(`${API}/${id}/brochures`, {
        method: 'POST',
        headers,
        body: formData,
      }).then((r) => {
        if (!r.ok) return r.json().then((e: { error?: string }) => { throw new Error(e.error || 'Upload failed'); });
        return r.json();
      });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['campaign-brochures', id] });
      setUploadFiles([]);
      toast.success('Brochure(s) uploaded');
    },
    onError: (err: Error) => toast.error(err.message),
  });

  const deleteBrochureMutation = useMutation({
    mutationFn: (brochureId: number) =>
      fetch(`${API}/${id}/brochures/${brochureId}`, {
        method: 'DELETE',
        headers: authHeaders(),
      }).then((r) => {
        if (!r.ok) return r.json().then((e: { error?: string }) => { throw new Error(e.error || 'Delete failed'); });
        return r.json();
      }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['campaign-brochures', id] });
      toast.success('Brochure removed');
    },
    onError: (err: Error) => toast.error(err.message),
  });

  /* ---- Handlers ---- */

  function handleSubmit() {
    if (!form.name.trim() || !form.campaign_type) {
      toast.error('Name and Campaign Type are required');
      return;
    }
    saveMutation.mutate({ data: form, asDraft: false });
  }

  function handleSaveDraft() {
    if (!form.name.trim()) {
      toast.error('Name is required');
      return;
    }
    saveMutation.mutate({ data: form, asDraft: true });
  }

  function handleFileSelect(e: React.ChangeEvent<HTMLInputElement>) {
    if (e.target.files) {
      const newFiles = Array.from(e.target.files);
      setUploadFiles((prev) => [...prev, ...newFiles]);
    }
  }

  function removeSelectedFile(index: number) {
    setUploadFiles((prev) => prev.filter((_, i) => i !== index));
  }

  function handleUploadBrochures() {
    if (uploadFiles.length === 0) return;
    uploadMutation.mutate(uploadFiles);
  }

  function formatFileSize(bytes: number): string {
    if (bytes < 1024) return `${bytes} B`;
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
    return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
  }

  /* ---- Loading state ---- */

  if (isEdit && loadingCampaign) {
    return (
      <div className="space-y-6">
        <div className="h-6 w-64 animate-pulse rounded bg-muted" />
        <div className="h-8 w-48 animate-pulse rounded bg-muted" />
        <Card>
          <CardContent className="py-12">
            <div className="flex flex-col items-center gap-2">
              <div className="h-8 w-8 animate-spin rounded-full border-4 border-primary border-t-transparent" />
              <p className="text-sm text-muted-foreground">Loading campaign...</p>
            </div>
          </CardContent>
        </Card>
      </div>
    );
  }

  /* ---- Render ---- */

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <Button variant="ghost" size="sm" onClick={() => navigate('/crm/campaigns')}>
            <ArrowLeft className="mr-1 h-4 w-4" /> Back
          </Button>
          <div>
            <h1 className="text-2xl font-bold">
              {isEdit ? 'Edit Campaign' : 'New Campaign'}
            </h1>
            {existingCampaign && (
              <div className="flex items-center gap-2 mt-1">
                <span className="text-sm text-muted-foreground font-mono">
                  {existingCampaign.campaign_code}
                </span>
                <Badge
                  className={statusColors[existingCampaign.status] || ''}
                  variant="secondary"
                >
                  {existingCampaign.status.replace(/_/g, ' ')}
                </Badge>
              </div>
            )}
          </div>
        </div>
        <div className="flex items-center gap-2">
          <Button
            variant="outline"
            onClick={handleSaveDraft}
            disabled={saveMutation.isPending}
          >
            <Save className="mr-1 h-4 w-4" />
            {saveMutation.isPending ? 'Saving...' : 'Save Draft'}
          </Button>
          <Button
            onClick={handleSubmit}
            disabled={saveMutation.isPending}
          >
            <Send className="mr-1 h-4 w-4" />
            {saveMutation.isPending ? 'Submitting...' : 'Submit'}
          </Button>
        </div>
      </div>

      {/* Tabs */}
      <Tabs value={activeTab} onValueChange={(v: string) => setActiveTab(v)}>
        <TabsList>
          <TabsTrigger value="general">General</TabsTrigger>
          <TabsTrigger value="financial">Financial</TabsTrigger>
          <TabsTrigger value="admin">Admin</TabsTrigger>
          <TabsTrigger value="notes">Campaign Notes</TabsTrigger>
          <TabsTrigger value="brochure">Brochure</TabsTrigger>
        </TabsList>

        {/* Tab 1: General */}
        <TabsContent value="general" className="mt-4">
          <Card>
            <CardHeader>
              <CardTitle className="text-base flex items-center gap-2">
                <Megaphone className="h-4 w-4" /> General Information
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              {/* Campaign Code (read-only, shown in edit mode) */}
              {isEdit && existingCampaign && (
                <div>
                  <label className="text-sm font-medium text-muted-foreground">Campaign Code</label>
                  <Input
                    value={existingCampaign.campaign_code}
                    disabled
                    className="font-mono bg-muted"
                  />
                  <p className="text-xs text-muted-foreground mt-1">Auto-generated by the system</p>
                </div>
              )}
              {!isEdit && (
                <div className="rounded-md border border-dashed p-3 bg-muted/30">
                  <p className="text-sm text-muted-foreground">
                    Campaign code will be auto-generated upon creation.
                  </p>
                </div>
              )}

              <div>
                <label className="text-sm font-medium">Campaign Name *</label>
                <Input
                  placeholder="e.g. Q2 2026 Product Launch"
                  value={form.name}
                  onChange={(e: React.ChangeEvent<HTMLInputElement>) => updateField('name', e.target.value)}
                />
              </div>

              <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
                <div>
                  <label className="text-sm font-medium">Campaign Type *</label>
                  <Select
                    value={form.campaign_type}
                    onValueChange={(v: string) => updateField('campaign_type', v)}
                  >
                    <SelectTrigger>
                      <SelectValue placeholder="Select type" />
                    </SelectTrigger>
                    <SelectContent>
                      {CAMPAIGN_TYPES.map((t) => (
                        <SelectItem key={t} value={t}>
                          {t.replace(/_/g, ' ')}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                <div>
                  <label className="text-sm font-medium">Channel</label>
                  <Select
                    value={form.channel}
                    onValueChange={(v: string) => updateField('channel', v)}
                  >
                    <SelectTrigger>
                      <SelectValue placeholder="Select channel" />
                    </SelectTrigger>
                    <SelectContent>
                      {CHANNELS.map((ch) => (
                        <SelectItem key={ch} value={ch}>{ch}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
              </div>

              <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
                <div>
                  <label className="text-sm font-medium">Start Date</label>
                  <Input
                    type="date"
                    value={form.start_date}
                    onChange={(e: React.ChangeEvent<HTMLInputElement>) => updateField('start_date', e.target.value)}
                  />
                </div>
                <div>
                  <label className="text-sm font-medium">End Date</label>
                  <Input
                    type="date"
                    value={form.end_date}
                    onChange={(e: React.ChangeEvent<HTMLInputElement>) => updateField('end_date', e.target.value)}
                  />
                </div>
              </div>

              <div>
                <label className="text-sm font-medium">Description</label>
                <textarea
                  className="flex min-h-[100px] w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                  placeholder="Brief description of the campaign objectives and scope"
                  value={form.description}
                  onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) => updateField('description', e.target.value)}
                />
              </div>

              {/* Status display (edit only) */}
              {isEdit && existingCampaign && (
                <div>
                  <label className="text-sm font-medium text-muted-foreground">Campaign Status</label>
                  <div className="mt-1">
                    <Badge
                      className={`${statusColors[existingCampaign.status] || ''} text-sm px-3 py-1`}
                      variant="secondary"
                    >
                      {existingCampaign.status.replace(/_/g, ' ')}
                    </Badge>
                  </div>
                </div>
              )}
            </CardContent>
          </Card>
        </TabsContent>

        {/* Tab 2: Financial */}
        <TabsContent value="financial" className="mt-4">
          <Card>
            <CardHeader>
              <CardTitle className="text-base">Financial Details</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
                <div>
                  <label className="text-sm font-medium">Budget Amount</label>
                  <Input
                    type="number"
                    step="0.01"
                    placeholder="0.00"
                    value={form.budget_amount}
                    onChange={(e: React.ChangeEvent<HTMLInputElement>) => updateField('budget_amount', e.target.value)}
                  />
                </div>
                <div>
                  <label className="text-sm font-medium">Budget Currency</label>
                  <Select
                    value={form.budget_currency}
                    onValueChange={(v: string) => updateField('budget_currency', v)}
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="PHP">PHP</SelectItem>
                      <SelectItem value="USD">USD</SelectItem>
                      <SelectItem value="EUR">EUR</SelectItem>
                      <SelectItem value="GBP">GBP</SelectItem>
                      <SelectItem value="JPY">JPY</SelectItem>
                      <SelectItem value="SGD">SGD</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>

              <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
                <div>
                  <label className="text-sm font-medium">Advertisement Cost</label>
                  <Input
                    type="number"
                    step="0.01"
                    placeholder="0.00"
                    value={form.advertisement_cost}
                    onChange={(e: React.ChangeEvent<HTMLInputElement>) => updateField('advertisement_cost', e.target.value)}
                  />
                  <p className="text-xs text-muted-foreground mt-1">
                    Cost allocated for advertising materials and placements
                  </p>
                </div>
                <div>
                  <label className="text-sm font-medium">Campaign Cost</label>
                  <Input
                    type="number"
                    step="0.01"
                    placeholder="0.00"
                    value={form.campaign_cost}
                    onChange={(e: React.ChangeEvent<HTMLInputElement>) => updateField('campaign_cost', e.target.value)}
                  />
                  <p className="text-xs text-muted-foreground mt-1">
                    Total operational cost of running the campaign
                  </p>
                </div>
              </div>

              {/* Summary */}
              {(form.budget_amount || form.advertisement_cost || form.campaign_cost) && (
                <div className="rounded-md border p-4 bg-muted/30">
                  <p className="text-sm font-medium mb-2">Financial Summary</p>
                  <div className="grid grid-cols-3 gap-4 text-sm">
                    <div>
                      <span className="text-muted-foreground">Budget</span>
                      <p className="font-mono font-medium">
                        {form.budget_currency} {form.budget_amount ? parseFloat(form.budget_amount).toLocaleString('en-PH', { minimumFractionDigits: 2 }) : '0.00'}
                      </p>
                    </div>
                    <div>
                      <span className="text-muted-foreground">Ad Cost</span>
                      <p className="font-mono font-medium">
                        {form.budget_currency} {form.advertisement_cost ? parseFloat(form.advertisement_cost).toLocaleString('en-PH', { minimumFractionDigits: 2 }) : '0.00'}
                      </p>
                    </div>
                    <div>
                      <span className="text-muted-foreground">Campaign Cost</span>
                      <p className="font-mono font-medium">
                        {form.budget_currency} {form.campaign_cost ? parseFloat(form.campaign_cost).toLocaleString('en-PH', { minimumFractionDigits: 2 }) : '0.00'}
                      </p>
                    </div>
                  </div>
                </div>
              )}
            </CardContent>
          </Card>
        </TabsContent>

        {/* Tab 3: Admin */}
        <TabsContent value="admin" className="mt-4">
          <Card>
            <CardHeader>
              <CardTitle className="text-base">Administration</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              {/* Lead List Selector */}
              <div>
                <label className="text-sm font-medium">Lead List</label>
                <div className="relative">
                  <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                  <Input
                    className="pl-9"
                    placeholder="Search lead lists..."
                    value={leadListSearch}
                    onChange={(e: React.ChangeEvent<HTMLInputElement>) => setLeadListSearch(e.target.value)}
                  />
                </div>
                <Select
                  value={form.lead_list_id}
                  onValueChange={(v: string) => updateField('lead_list_id', v)}
                >
                  <SelectTrigger className="mt-2">
                    <SelectValue placeholder="Select a lead list" />
                  </SelectTrigger>
                  <SelectContent>
                    {leadLists.length === 0 ? (
                      <div className="px-3 py-4 text-center text-sm text-muted-foreground">
                        No lead lists found
                      </div>
                    ) : (
                      leadLists.map((list: LeadListOption) => (
                        <SelectItem key={list.id} value={list.id.toString()}>
                          <div className="flex items-center gap-2">
                            <span>{list.name}</span>
                            <span className="text-xs text-muted-foreground">
                              ({list.total_count} leads, {list.source_type.replace(/_/g, ' ')})
                            </span>
                          </div>
                        </SelectItem>
                      ))
                    )}
                  </SelectContent>
                </Select>
                <p className="text-xs text-muted-foreground mt-1">
                  Assign a target lead list for this campaign
                </p>
              </div>

              {/* Campaign Manager */}
              <div>
                <label className="text-sm font-medium">Campaign Manager ID</label>
                <Input
                  placeholder="Enter manager user ID or employee number"
                  value={form.campaign_manager_id}
                  onChange={(e: React.ChangeEvent<HTMLInputElement>) => updateField('campaign_manager_id', e.target.value)}
                />
                <p className="text-xs text-muted-foreground mt-1">
                  Assign the RM or campaign manager responsible for this campaign
                </p>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        {/* Tab 4: Campaign Notes */}
        <TabsContent value="notes" className="mt-4">
          <Card>
            <CardHeader>
              <CardTitle className="text-base">Campaign Notes & Content</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <label className="text-sm font-medium">Email Subject</label>
                <Input
                  placeholder="Subject line for campaign emails"
                  value={form.email_subject}
                  onChange={(e: React.ChangeEvent<HTMLInputElement>) => updateField('email_subject', e.target.value)}
                />
              </div>

              <div>
                <label className="text-sm font-medium">Email Body</label>
                <textarea
                  className="flex min-h-[160px] w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                  placeholder="Main body content for campaign email..."
                  value={form.email_body}
                  onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) => updateField('email_body', e.target.value)}
                />
              </div>

              <div>
                <label className="text-sm font-medium">Email Signature</label>
                <textarea
                  className="flex min-h-[80px] w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                  placeholder="Signature block for campaign emails..."
                  value={form.email_signature}
                  onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) => updateField('email_signature', e.target.value)}
                />
              </div>

              <div className="border-t pt-4">
                <label className="text-sm font-medium">SMS Content</label>
                <textarea
                  className="flex min-h-[100px] w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                  placeholder="SMS message content (max 160 characters recommended)..."
                  value={form.sms_content}
                  onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) => updateField('sms_content', e.target.value)}
                />
                <p className="text-xs text-muted-foreground mt-1">
                  {form.sms_content.length} characters
                  {form.sms_content.length > 160 && (
                    <span className="text-yellow-600 dark:text-yellow-400"> -- exceeds single SMS limit</span>
                  )}
                </p>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        {/* Tab 5: Brochure */}
        <TabsContent value="brochure" className="mt-4">
          <Card>
            <CardHeader>
              <CardTitle className="text-base flex items-center gap-2">
                <FileText className="h-4 w-4" /> Brochure Attachments
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              {/* Upload Area */}
              <div className="rounded-md border-2 border-dashed p-6 text-center">
                <Upload className="mx-auto h-8 w-8 text-muted-foreground/50 mb-2" />
                <p className="text-sm text-muted-foreground mb-3">
                  Drag & drop files here, or click to browse
                </p>
                <input
                  type="file"
                  multiple
                  onChange={handleFileSelect}
                  className="hidden"
                  id="brochure-upload"
                  accept=".pdf,.doc,.docx,.ppt,.pptx,.jpg,.jpeg,.png"
                />
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => document.getElementById('brochure-upload')?.click()}
                >
                  <Upload className="mr-1 h-4 w-4" /> Browse Files
                </Button>
                <p className="text-xs text-muted-foreground mt-2">
                  Supported: PDF, DOC, DOCX, PPT, PPTX, JPG, PNG
                </p>
              </div>

              {/* Selected files (pending upload) */}
              {uploadFiles.length > 0 && (
                <div className="space-y-2">
                  <p className="text-sm font-medium">Selected Files ({uploadFiles.length})</p>
                  <div className="rounded-md border divide-y">
                    {uploadFiles.map((file, idx) => (
                      <div key={idx} className="flex items-center justify-between px-3 py-2">
                        <div className="flex items-center gap-2 min-w-0">
                          <FileText className="h-4 w-4 text-muted-foreground flex-shrink-0" />
                          <span className="text-sm truncate">{file.name}</span>
                          <span className="text-xs text-muted-foreground flex-shrink-0">
                            ({formatFileSize(file.size)})
                          </span>
                        </div>
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => removeSelectedFile(idx)}
                        >
                          <X className="h-3 w-3" />
                        </Button>
                      </div>
                    ))}
                  </div>
                  {isEdit && (
                    <Button
                      size="sm"
                      onClick={handleUploadBrochures}
                      disabled={uploadMutation.isPending}
                    >
                      <Upload className="mr-1 h-4 w-4" />
                      {uploadMutation.isPending ? 'Uploading...' : `Upload ${uploadFiles.length} File(s)`}
                    </Button>
                  )}
                  {!isEdit && (
                    <p className="text-xs text-muted-foreground">
                      Files will be uploaded after the campaign is created. Save the campaign first.
                    </p>
                  )}
                </div>
              )}

              {/* Existing brochures */}
              {isEdit && (
                <div className="space-y-2">
                  <p className="text-sm font-medium">Uploaded Brochures</p>
                  {brochuresLoading ? (
                    <div className="space-y-2">
                      {Array.from({ length: 3 }).map((_, i) => (
                        <div key={i} className="h-10 w-full animate-pulse rounded bg-muted" />
                      ))}
                    </div>
                  ) : brochures.length === 0 ? (
                    <div className="rounded-md border p-6 text-center text-muted-foreground">
                      <FileText className="mx-auto h-8 w-8 text-muted-foreground/50 mb-2" />
                      <p className="text-sm">No brochures uploaded yet</p>
                    </div>
                  ) : (
                    <div className="rounded-md border divide-y">
                      {brochures.map((file: BrochureFile) => (
                        <div key={file.id} className="flex items-center justify-between px-3 py-2">
                          <div className="flex items-center gap-2 min-w-0">
                            <FileText className="h-4 w-4 text-blue-600 dark:text-blue-400 flex-shrink-0" />
                            <span className="text-sm truncate">{file.filename}</span>
                            <span className="text-xs text-muted-foreground flex-shrink-0">
                              ({formatFileSize(file.size)})
                            </span>
                            <span className="text-xs text-muted-foreground flex-shrink-0">
                              {new Date(file.uploaded_at).toLocaleDateString()}
                            </span>
                          </div>
                          <Button
                            variant="ghost"
                            size="sm"
                            className="text-destructive hover:text-destructive"
                            disabled={deleteBrochureMutation.isPending}
                            onClick={() => {
                              if (window.confirm('Remove this brochure?')) {
                                deleteBrochureMutation.mutate(file.id);
                              }
                            }}
                          >
                            <Trash2 className="h-3 w-3" />
                          </Button>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              )}
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}
