-- Margin Lending module from WQ Margin Lending V1.0 CCV1.0

CREATE TABLE IF NOT EXISTS ml_attribute_settings (
  id serial PRIMARY KEY,
  setting_id text NOT NULL UNIQUE,
  maintenance_type text NOT NULL,
  definition_type text NOT NULL,
  asset_class text,
  sub_asset_classes jsonb NOT NULL DEFAULT '[]'::jsonb,
  currencies jsonb NOT NULL DEFAULT '[]'::jsonb,
  industry_codes jsonb NOT NULL DEFAULT '[]'::jsonb,
  market_groups jsonb NOT NULL DEFAULT '[]'::jsonb,
  security_domiciles jsonb NOT NULL DEFAULT '[]'::jsonb,
  security_issuers jsonb NOT NULL DEFAULT '[]'::jsonb,
  rating_agencies jsonb NOT NULL DEFAULT '[]'::jsonb,
  ratings jsonb NOT NULL DEFAULT '[]'::jsonb,
  residual_tenors jsonb NOT NULL DEFAULT '[]'::jsonb,
  issuer_categories jsonb NOT NULL DEFAULT '[]'::jsonb,
  capital_protection text,
  fund_domiciles jsonb NOT NULL DEFAULT '[]'::jsonb,
  security_risk_profiles jsonb NOT NULL DEFAULT '[]'::jsonb,
  fund_houses jsonb NOT NULL DEFAULT '[]'::jsonb,
  ltv_percent numeric(9,4) NOT NULL,
  top_up_percent numeric(9,4) NOT NULL,
  sell_out_percent numeric(9,4) NOT NULL,
  record_status text NOT NULL DEFAULT 'DRAFT',
  effective_from date NOT NULL,
  effective_to date,
  submitted_by text,
  submitted_at timestamptz,
  authorized_by text,
  authorized_at timestamptz,
  rejected_by text,
  rejected_at timestamptz,
  rejected_reason text,
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by text,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by text,
  version integer NOT NULL DEFAULT 1,
  status text NOT NULL DEFAULT 'active',
  is_deleted boolean NOT NULL DEFAULT false,
  tenant_id text NOT NULL DEFAULT 'default',
  correlation_id text,
  audit_hash text
);

CREATE TABLE IF NOT EXISTS ml_references (
  id serial PRIMARY KEY,
  reference_id text NOT NULL UNIQUE,
  reference_type text NOT NULL,
  reference_code text NOT NULL,
  reference_value text NOT NULL,
  reference_value_numeric numeric(21,8),
  record_status text NOT NULL DEFAULT 'DRAFT',
  effective_from date NOT NULL,
  effective_to date,
  authorized_by text,
  authorized_at timestamptz,
  rejected_reason text,
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by text,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by text,
  version integer NOT NULL DEFAULT 1,
  status text NOT NULL DEFAULT 'active',
  is_deleted boolean NOT NULL DEFAULT false,
  tenant_id text NOT NULL DEFAULT 'default',
  correlation_id text,
  audit_hash text
);

CREATE TABLE IF NOT EXISTS ml_scrip_settings (
  id serial PRIMARY KEY,
  scrip_setting_id text NOT NULL UNIQUE,
  security_id integer REFERENCES securities(id),
  security_code text NOT NULL,
  security_name text NOT NULL,
  currency text,
  issuer_code text,
  security_concentration_flag boolean NOT NULL DEFAULT false,
  inheritance_flag boolean NOT NULL DEFAULT true,
  ltv_percent numeric(9,4),
  top_up_percent numeric(9,4),
  sell_out_percent numeric(9,4),
  record_status text NOT NULL DEFAULT 'DRAFT',
  effective_from date NOT NULL,
  effective_to date,
  authorized_by text,
  authorized_at timestamptz,
  rejected_reason text,
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by text,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by text,
  version integer NOT NULL DEFAULT 1,
  status text NOT NULL DEFAULT 'active',
  is_deleted boolean NOT NULL DEFAULT false,
  tenant_id text NOT NULL DEFAULT 'default',
  correlation_id text,
  audit_hash text
);

CREATE TABLE IF NOT EXISTS ml_exposure_limits (
  id serial PRIMARY KEY,
  exposure_limit_id text NOT NULL UNIQUE,
  limit_code text NOT NULL,
  limit_name text NOT NULL,
  currency text NOT NULL,
  amount numeric(21,4) NOT NULL,
  threshold_percent numeric(9,4) NOT NULL,
  category text NOT NULL,
  sub_category text,
  category_values jsonb NOT NULL DEFAULT '[]'::jsonb,
  sub_category_values jsonb NOT NULL DEFAULT '[]'::jsonb,
  record_status text NOT NULL DEFAULT 'DRAFT',
  effective_from date NOT NULL,
  effective_to date,
  authorized_by text,
  authorized_at timestamptz,
  rejected_reason text,
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by text,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by text,
  version integer NOT NULL DEFAULT 1,
  status text NOT NULL DEFAULT 'active',
  is_deleted boolean NOT NULL DEFAULT false,
  tenant_id text NOT NULL DEFAULT 'default',
  correlation_id text,
  audit_hash text
);

CREATE TABLE IF NOT EXISTS ml_cross_currency_haircuts (
  id serial PRIMARY KEY,
  haircut_id text NOT NULL UNIQUE,
  source_currency text NOT NULL,
  target_currency text NOT NULL,
  buffer_percent numeric(9,4) NOT NULL,
  volatility_percent numeric(9,4) NOT NULL,
  haircut_percent numeric(9,4) NOT NULL,
  record_status text NOT NULL DEFAULT 'DRAFT',
  effective_from date NOT NULL,
  effective_to date,
  authorized_by text,
  authorized_at timestamptz,
  rejected_reason text,
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by text,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by text,
  version integer NOT NULL DEFAULT 1,
  status text NOT NULL DEFAULT 'active',
  is_deleted boolean NOT NULL DEFAULT false,
  tenant_id text NOT NULL DEFAULT 'default',
  correlation_id text,
  audit_hash text
);

CREATE TABLE IF NOT EXISTS ml_facility_groups (
  id serial PRIMARY KEY,
  facility_group_id text NOT NULL UNIQUE,
  base_number text NOT NULL,
  base_name text NOT NULL,
  customer_id text REFERENCES clients(client_id),
  description text,
  start_date date NOT NULL,
  maturity_date date NOT NULL,
  limit_amount numeric(21,4) NOT NULL,
  utilized_amount numeric(21,4) NOT NULL DEFAULT 0,
  available_drawing_power numeric(21,4) NOT NULL DEFAULT 0,
  currency text NOT NULL,
  record_status text NOT NULL DEFAULT 'DRAFT',
  authorized_by text,
  authorized_at timestamptz,
  rejected_reason text,
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by text,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by text,
  version integer NOT NULL DEFAULT 1,
  status text NOT NULL DEFAULT 'active',
  is_deleted boolean NOT NULL DEFAULT false,
  tenant_id text NOT NULL DEFAULT 'default',
  correlation_id text,
  audit_hash text
);

CREATE TABLE IF NOT EXISTS ml_facilities (
  id serial PRIMARY KEY,
  facility_id text NOT NULL UNIQUE,
  facility_group_id text NOT NULL REFERENCES ml_facility_groups(facility_group_id),
  source_system text NOT NULL,
  source_facility_ref text NOT NULL,
  asset_class text NOT NULL,
  sub_asset_class text,
  currency text NOT NULL,
  limit_amount numeric(21,4) NOT NULL,
  utilized_amount numeric(21,4) NOT NULL DEFAULT 0,
  available_amount numeric(21,4) NOT NULL DEFAULT 0,
  facility_status text NOT NULL DEFAULT 'ACTIVE',
  imported_at timestamptz NOT NULL DEFAULT now(),
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by text,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by text,
  version integer NOT NULL DEFAULT 1,
  status text NOT NULL DEFAULT 'active',
  is_deleted boolean NOT NULL DEFAULT false,
  tenant_id text NOT NULL DEFAULT 'default',
  correlation_id text,
  audit_hash text
);

CREATE TABLE IF NOT EXISTS ml_portfolio_links (
  id serial PRIMARY KEY,
  portfolio_link_id text NOT NULL UNIQUE,
  facility_group_id text NOT NULL REFERENCES ml_facility_groups(facility_group_id),
  base_number text NOT NULL,
  portfolio_id text NOT NULL REFERENCES portfolios(portfolio_id),
  linked_flag boolean NOT NULL DEFAULT true,
  cross_pledge_flag boolean NOT NULL DEFAULT false,
  pledgor_base_number text,
  priority integer NOT NULL DEFAULT 1,
  ownership_evidence_ref text,
  pledge_status text NOT NULL DEFAULT 'AVAILABLE',
  record_status text NOT NULL DEFAULT 'DRAFT',
  authorized_by text,
  authorized_at timestamptz,
  rejected_reason text,
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by text,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by text,
  version integer NOT NULL DEFAULT 1,
  status text NOT NULL DEFAULT 'active',
  is_deleted boolean NOT NULL DEFAULT false,
  tenant_id text NOT NULL DEFAULT 'default',
  correlation_id text,
  audit_hash text
);

CREATE TABLE IF NOT EXISTS ml_asset_settings (
  id serial PRIMARY KEY,
  asset_setting_id text NOT NULL UNIQUE,
  base_number text NOT NULL,
  customer_id text REFERENCES clients(client_id),
  security_id integer REFERENCES securities(id),
  security_code text NOT NULL,
  security_name text NOT NULL,
  inheritance_flag boolean NOT NULL DEFAULT true,
  issuer_concentration_percent numeric(9,4),
  security_concentration_percent numeric(9,4),
  ltv_percent numeric(9,4),
  top_up_percent numeric(9,4),
  sell_out_percent numeric(9,4),
  record_status text NOT NULL DEFAULT 'DRAFT',
  effective_from date NOT NULL,
  effective_to date,
  authorized_by text,
  authorized_at timestamptz,
  rejected_reason text,
  remarks text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by text,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by text,
  version integer NOT NULL DEFAULT 1,
  status text NOT NULL DEFAULT 'active',
  is_deleted boolean NOT NULL DEFAULT false,
  tenant_id text NOT NULL DEFAULT 'default',
  correlation_id text,
  audit_hash text
);

CREATE TABLE IF NOT EXISTS ml_margin_call_cases (
  id serial PRIMARY KEY,
  case_id text NOT NULL UNIQUE,
  facility_group_id text REFERENCES ml_facility_groups(facility_group_id),
  base_number text NOT NULL,
  portfolio_id text REFERENCES portfolios(portfolio_id),
  security_code text,
  case_level text NOT NULL DEFAULT 'PORTFOLIO',
  case_status text NOT NULL DEFAULT 'OPEN',
  margin_status text NOT NULL,
  business_date date NOT NULL,
  market_value numeric(21,4) NOT NULL,
  gcmv_amount numeric(21,4) NOT NULL,
  exposure_amount numeric(21,4) NOT NULL,
  ncmv_amount numeric(21,4) NOT NULL,
  top_up_amount numeric(21,4) NOT NULL,
  sell_out_amount numeric(21,4) NOT NULL,
  shortfall_amount numeric(21,4) NOT NULL DEFAULT 0,
  advice_reference text,
  advice_status text NOT NULL DEFAULT 'NOT_GENERATED',
  notice_due_date date,
  deferral_expiry_date date,
  closure_remarks text,
  pending_action_type text,
  last_action_by text,
  last_action_at timestamptz,
  authorized_by text,
  authorized_at timestamptz,
  rejected_reason text,
  source_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by text,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by text,
  version integer NOT NULL DEFAULT 1,
  status text NOT NULL DEFAULT 'active',
  is_deleted boolean NOT NULL DEFAULT false,
  tenant_id text NOT NULL DEFAULT 'default',
  correlation_id text,
  audit_hash text
);

CREATE TABLE IF NOT EXISTS ml_margin_call_actions (
  id serial PRIMARY KEY,
  action_id text NOT NULL UNIQUE,
  case_id text NOT NULL REFERENCES ml_margin_call_cases(case_id),
  action_type text NOT NULL,
  action_status text NOT NULL DEFAULT 'UNAUTHORIZED',
  deferral_expiry_date date,
  reason text,
  remarks text,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  authorized_by text,
  authorized_at timestamptz,
  rejected_reason text,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by text,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by text,
  version integer NOT NULL DEFAULT 1,
  status text NOT NULL DEFAULT 'active',
  is_deleted boolean NOT NULL DEFAULT false,
  tenant_id text NOT NULL DEFAULT 'default',
  correlation_id text,
  audit_hash text
);

CREATE TABLE IF NOT EXISTS ml_eod_runs (
  id serial PRIMARY KEY,
  eod_run_id text NOT NULL UNIQUE,
  job_id text NOT NULL,
  job_type text NOT NULL,
  business_date date NOT NULL,
  run_status text NOT NULL DEFAULT 'RUNNING',
  started_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  processed_count integer NOT NULL DEFAULT 0,
  failed_count integer NOT NULL DEFAULT 0,
  error_reason text,
  source_status text NOT NULL DEFAULT 'AVAILABLE',
  result_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by text,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by text,
  version integer NOT NULL DEFAULT 1,
  status text NOT NULL DEFAULT 'active',
  is_deleted boolean NOT NULL DEFAULT false,
  tenant_id text NOT NULL DEFAULT 'default',
  correlation_id text,
  audit_hash text
);

CREATE TABLE IF NOT EXISTS ml_simulation_runs (
  id serial PRIMARY KEY,
  simulation_id text NOT NULL UNIQUE,
  simulation_type text NOT NULL DEFAULT 'CUSTOMER',
  base_number text NOT NULL,
  facility_group_id text REFERENCES ml_facility_groups(facility_group_id),
  business_date date NOT NULL,
  input_payload jsonb NOT NULL,
  before_metrics jsonb NOT NULL,
  after_metrics jsonb NOT NULL,
  comparison_payload jsonb NOT NULL,
  run_status text NOT NULL DEFAULT 'COMPLETED',
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by text,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by text,
  version integer NOT NULL DEFAULT 1,
  status text NOT NULL DEFAULT 'active',
  is_deleted boolean NOT NULL DEFAULT false,
  tenant_id text NOT NULL DEFAULT 'default',
  correlation_id text,
  audit_hash text
);

CREATE TABLE IF NOT EXISTS ml_audit_events (
  id serial PRIMARY KEY,
  event_id text NOT NULL UNIQUE,
  entity_type text NOT NULL,
  entity_id text NOT NULL,
  action text NOT NULL,
  actor_user_id text NOT NULL,
  actor_role text,
  event_time timestamptz NOT NULL DEFAULT now(),
  before_payload jsonb,
  after_payload jsonb,
  decision text,
  reason text,
  source_ip text,
  masked_payload jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by text,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by text,
  version integer NOT NULL DEFAULT 1,
  status text NOT NULL DEFAULT 'active',
  is_deleted boolean NOT NULL DEFAULT false,
  tenant_id text NOT NULL DEFAULT 'default',
  correlation_id text,
  audit_hash text
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_ml_reference_type_code ON ml_references(reference_type, reference_code);
CREATE UNIQUE INDEX IF NOT EXISTS ux_ml_exposure_limit_code ON ml_exposure_limits(limit_code);
CREATE UNIQUE INDEX IF NOT EXISTS ux_ml_haircut_currency_pair ON ml_cross_currency_haircuts(source_currency, target_currency);
CREATE UNIQUE INDEX IF NOT EXISTS ux_ml_eod_idempotency ON ml_eod_runs(job_id, job_type, business_date);

CREATE INDEX IF NOT EXISTS idx_ml_attribute_settings_type_status ON ml_attribute_settings(maintenance_type, record_status);
CREATE INDEX IF NOT EXISTS idx_ml_attribute_settings_effective ON ml_attribute_settings(effective_from, effective_to);
CREATE INDEX IF NOT EXISTS idx_ml_references_type_status ON ml_references(reference_type, record_status);
CREATE INDEX IF NOT EXISTS idx_ml_scrip_settings_security ON ml_scrip_settings(security_code, record_status);
CREATE INDEX IF NOT EXISTS idx_ml_exposure_limits_scope ON ml_exposure_limits(category, sub_category, record_status);
CREATE INDEX IF NOT EXISTS idx_ml_exposure_limits_effective ON ml_exposure_limits(effective_from, effective_to);
CREATE INDEX IF NOT EXISTS idx_ml_haircuts_status ON ml_cross_currency_haircuts(record_status);
CREATE INDEX IF NOT EXISTS idx_ml_facility_groups_base ON ml_facility_groups(base_number, record_status);
CREATE INDEX IF NOT EXISTS idx_ml_facility_groups_customer ON ml_facility_groups(customer_id);
CREATE INDEX IF NOT EXISTS idx_ml_facilities_group_status ON ml_facilities(facility_group_id, facility_status);
CREATE INDEX IF NOT EXISTS idx_ml_facilities_source ON ml_facilities(source_system, source_facility_ref);
CREATE INDEX IF NOT EXISTS idx_ml_portfolio_links_group ON ml_portfolio_links(facility_group_id, record_status);
CREATE INDEX IF NOT EXISTS idx_ml_portfolio_links_portfolio ON ml_portfolio_links(portfolio_id, cross_pledge_flag);
CREATE INDEX IF NOT EXISTS idx_ml_asset_settings_base_security ON ml_asset_settings(base_number, security_code, record_status);
CREATE INDEX IF NOT EXISTS idx_ml_margin_cases_group_date ON ml_margin_call_cases(facility_group_id, business_date);
CREATE INDEX IF NOT EXISTS idx_ml_margin_cases_status ON ml_margin_call_cases(case_status, margin_status);
CREATE INDEX IF NOT EXISTS idx_ml_margin_cases_portfolio ON ml_margin_call_cases(portfolio_id);
CREATE INDEX IF NOT EXISTS idx_ml_margin_actions_case ON ml_margin_call_actions(case_id, action_status);
CREATE INDEX IF NOT EXISTS idx_ml_eod_runs_status ON ml_eod_runs(run_status, business_date);
CREATE INDEX IF NOT EXISTS idx_ml_simulations_base_date ON ml_simulation_runs(base_number, business_date);
CREATE INDEX IF NOT EXISTS idx_ml_audit_entity ON ml_audit_events(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_ml_audit_actor_time ON ml_audit_events(actor_user_id, event_time);
