import type { EntityFieldDefaults } from './types';

export const branchFieldConfig: EntityFieldDefaults = {
  fields: {
    code: {
      label: 'Branch Code',
      group: 'Basic Info',
      groupOrder: 1,
      displayOrder: 1,
      inputType: 'text',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      uniqueCheck: true,
      maxLength: 20,
      placeholder: 'e.g. MNL-HQ',
    },
    name: {
      label: 'Branch Name',
      group: 'Basic Info',
      groupOrder: 1,
      displayOrder: 2,
      inputType: 'text',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      placeholder: 'e.g. Manila Head Office',
    },
    address: {
      label: 'Address',
      group: 'Location',
      groupOrder: 2,
      displayOrder: 3,
      inputType: 'textarea',
      required: false,
      visibleInTable: false,
      visibleInForm: true,
      sortable: false,
      placeholder: 'Full branch address',
    },
    region: {
      label: 'Region',
      group: 'Location',
      groupOrder: 2,
      displayOrder: 4,
      inputType: 'text',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      placeholder: 'e.g. NCR',
    },
  },
  fieldGroups: ['Basic Info', 'Location'],
};
