import type { EntityFieldDefaults } from './types';

export const clientFieldConfig: EntityFieldDefaults = {
  fields: {
    client_id: {
      label: 'Client ID',
      group: 'Personal Info',
      groupOrder: 1,
      displayOrder: 1,
      inputType: 'text',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      uniqueCheck: true,
      placeholder: 'e.g. CL-00001',
      helpText: 'Unique client identifier',
    },
    legal_name: {
      label: 'Legal Name',
      group: 'Personal Info',
      groupOrder: 1,
      displayOrder: 2,
      inputType: 'text',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      piiSensitive: true,
      piiClassification: 'PII',
      dataResidency: 'PH-only',
      placeholder: 'Full legal name of the client',
    },
    type: {
      label: 'Client Type',
      group: 'Personal Info',
      groupOrder: 1,
      displayOrder: 3,
      inputType: 'select',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      selectOptionsSource: 'INDIVIDUAL,CORPORATE,TRUST',
    },
    tin: {
      label: 'TIN',
      group: 'Personal Info',
      groupOrder: 1,
      displayOrder: 4,
      inputType: 'tin',
      required: false,
      visibleInTable: false,
      visibleInForm: true,
      sortable: false,
      piiSensitive: true,
      piiClassification: 'Sensitive-PII',
      dataResidency: 'PH-only',
      placeholder: 'Tax Identification Number',
      helpText: 'Philippine TIN (XXX-XXX-XXX-XXX)',
    },
    birth_date: {
      label: 'Date of Birth',
      group: 'Personal Info',
      groupOrder: 1,
      displayOrder: 5,
      inputType: 'date',
      required: false,
      visibleInTable: false,
      visibleInForm: true,
      sortable: false,
      piiSensitive: true,
      piiClassification: 'PII',
      dataResidency: 'PH-only',
    },
    address: {
      label: 'Address',
      group: 'Contact',
      groupOrder: 2,
      displayOrder: 6,
      inputType: 'textarea',
      required: false,
      visibleInTable: false,
      visibleInForm: true,
      sortable: false,
      piiSensitive: true,
      piiClassification: 'PII',
      dataResidency: 'PH-only',
      placeholder: 'Full address (JSON format for structured address)',
    },
    contact: {
      label: 'Contact Information',
      group: 'Contact',
      groupOrder: 2,
      displayOrder: 7,
      inputType: 'textarea',
      required: false,
      visibleInTable: false,
      visibleInForm: true,
      sortable: false,
      piiSensitive: true,
      piiClassification: 'PII',
      dataResidency: 'PH-only',
      placeholder: 'Contact details (phone, email, etc.)',
    },
    risk_profile: {
      label: 'Risk Profile',
      group: 'Risk & Suitability',
      groupOrder: 3,
      displayOrder: 8,
      inputType: 'select',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      selectOptionsSource: 'CONSERVATIVE,MODERATE,BALANCED,GROWTH,AGGRESSIVE',
      helpText: 'Client risk tolerance classification',
    },
    client_status: {
      label: 'Status',
      group: 'Status',
      groupOrder: 4,
      displayOrder: 9,
      inputType: 'select',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      selectOptionsSource: 'ACTIVE,INACTIVE,SUSPENDED,PENDING_KYC,CLOSED',
    },
  },
  fieldGroups: ['Personal Info', 'Contact', 'Risk & Suitability', 'Status'],
};
