import type { EntityFieldDefaults } from './types';

export const complianceLimitFieldConfig: EntityFieldDefaults = {
  fields: {
    limit_type: {
      label: 'Limit Type',
      group: 'Limit Definition',
      groupOrder: 1,
      displayOrder: 1,
      inputType: 'select',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      selectOptions: [
        { value: 'trader', label: 'Trader' },
        { value: 'counterparty', label: 'Counterparty' },
        { value: 'broker', label: 'Broker' },
        { value: 'issuer', label: 'Issuer' },
        { value: 'sector', label: 'Sector' },
        { value: 'sbl', label: 'Single Borrower Limit' },
        { value: 'group', label: 'Group' },
        { value: 'outlet', label: 'Outlet/Security' },
      ],
    },
    dimension: {
      label: 'Dimension',
      group: 'Limit Definition',
      groupOrder: 1,
      displayOrder: 2,
      inputType: 'text',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      placeholder: 'e.g. Asset Class, Currency',
    },
    dimension_id: {
      label: 'Dimension ID',
      group: 'Limit Definition',
      groupOrder: 1,
      displayOrder: 3,
      inputType: 'text',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: false,
      placeholder: 'e.g. Specific entity ID',
    },
    limit_amount: {
      label: 'Limit Amount',
      group: 'Thresholds',
      groupOrder: 2,
      displayOrder: 4,
      inputType: 'number',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
    },
    current_exposure: {
      label: 'Current Exposure',
      group: 'Thresholds',
      groupOrder: 2,
      displayOrder: 5,
      inputType: 'number',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
    },
    warning_threshold_pct: {
      label: 'Warning Threshold %',
      group: 'Thresholds',
      groupOrder: 2,
      displayOrder: 6,
      inputType: 'number',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: false,
      helpText: 'Alert when exposure exceeds this % of limit (default 80%)',
    },
    is_active: {
      label: 'Active',
      group: 'Limit Definition',
      groupOrder: 1,
      displayOrder: 7,
      inputType: 'switch',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
    },
    effective_from: {
      label: 'Effective From',
      group: 'Validity',
      groupOrder: 3,
      displayOrder: 8,
      inputType: 'date',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
    },
    effective_to: {
      label: 'Effective To',
      group: 'Validity',
      groupOrder: 3,
      displayOrder: 9,
      inputType: 'date',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
    },
  },
  fieldGroups: ['Limit Definition', 'Thresholds', 'Validity'],
};
