import type { EntityFieldDefaults } from './types';

export const counterpartyFieldConfig: EntityFieldDefaults = {
  fields: {
    name: {
      label: 'Counterparty Name',
      group: 'Basic Info',
      groupOrder: 1,
      displayOrder: 1,
      inputType: 'text',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      placeholder: 'e.g. Bank of the Philippine Islands',
    },
    lei: {
      label: 'LEI',
      group: 'Basic Info',
      groupOrder: 1,
      displayOrder: 2,
      inputType: 'text',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: false,
      maxLength: 20,
      placeholder: 'Legal Entity Identifier (20 chars)',
      helpText: 'ISO 17442 Legal Entity Identifier',
    },
    bic: {
      label: 'BIC / SWIFT Code',
      group: 'Settlement',
      groupOrder: 2,
      displayOrder: 3,
      inputType: 'text',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: false,
      maxLength: 11,
      placeholder: 'e.g. BOPIPHMM',
      helpText: 'SWIFT/BIC code for settlement',
    },
    type: {
      label: 'Type',
      group: 'Basic Info',
      groupOrder: 1,
      displayOrder: 4,
      inputType: 'select',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      selectOptionsSource: 'BANK,BROKER,CUSTODIAN,EXCHANGE',
    },
    is_active: {
      label: 'Active',
      group: 'Settlement',
      groupOrder: 2,
      displayOrder: 5,
      inputType: 'switch',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
    },
  },
  fieldGroups: ['Basic Info', 'Settlement'],
};
