import type { EntityFieldDefaults } from './types';

export const currencyFieldConfig: EntityFieldDefaults = {
  fields: {
    code: {
      label: 'Currency Code',
      group: 'Basic Info',
      groupOrder: 1,
      displayOrder: 1,
      inputType: 'text',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      uniqueCheck: true,
      maxLength: 3,
      placeholder: 'e.g. PHP',
      helpText: 'ISO 4217 currency code',
    },
    name: {
      label: 'Currency Name',
      group: 'Basic Info',
      groupOrder: 1,
      displayOrder: 2,
      inputType: 'text',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      placeholder: 'e.g. Philippine Peso',
    },
    symbol: {
      label: 'Symbol',
      group: 'Settings',
      groupOrder: 2,
      displayOrder: 3,
      inputType: 'text',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: false,
      maxLength: 5,
      placeholder: 'e.g. ₱',
    },
    decimal_places: {
      label: 'Decimal Places',
      group: 'Settings',
      groupOrder: 2,
      displayOrder: 4,
      inputType: 'number',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: false,
      minValue: 0,
      maxValue: 8,
      helpText: 'Number of decimal places for this currency (default: 2)',
    },
  },
  fieldGroups: ['Basic Info', 'Settings'],
};
