import type { EntityFieldDefaults } from './types';

export const dataStewardshipFieldConfig: EntityFieldDefaults = {
  fields: {
    dataset_key: {
      label: 'Dataset Key',
      group: 'Stewardship Info',
      groupOrder: 1,
      displayOrder: 1,
      inputType: 'text',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      uniqueCheck: true,
      placeholder: 'e.g. ca_type, tax_rule, market_calendar',
    },
    steward_user_id: {
      label: 'Steward User ID',
      group: 'Stewardship Info',
      groupOrder: 1,
      displayOrder: 2,
      inputType: 'number',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: false,
    },
    approval_policy: {
      label: 'Approval Policy',
      group: 'Stewardship Info',
      groupOrder: 1,
      displayOrder: 3,
      inputType: 'select',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      selectOptionsSource: 'SINGLE_APPROVER,DUAL_APPROVAL,COMMITTEE_APPROVAL',
    },
    change_frequency_cap: {
      label: 'Change Frequency',
      group: 'Stewardship Info',
      groupOrder: 1,
      displayOrder: 4,
      inputType: 'select',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: false,
      selectOptionsSource: 'Daily,Weekly,Monthly,Quarterly',
    },
    last_reviewed_at: {
      label: 'Last Reviewed',
      group: 'Stewardship Info',
      groupOrder: 1,
      displayOrder: 5,
      inputType: 'date',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
    },
  },
  fieldGroups: ['Stewardship Info'],
};
