import type { EntityFieldDefaults } from './types';

export const exchangeFieldConfig: EntityFieldDefaults = {
  fields: {
    code: {
      label: 'Exchange Code',
      group: 'Basic Info',
      groupOrder: 1,
      displayOrder: 1,
      inputType: 'text',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      uniqueCheck: true,
      maxLength: 10,
      placeholder: 'e.g. PSE',
    },
    name: {
      label: 'Exchange Name',
      group: 'Basic Info',
      groupOrder: 1,
      displayOrder: 2,
      inputType: 'text',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      placeholder: 'e.g. Philippine Stock Exchange',
    },
    country_code: {
      label: 'Country Code',
      group: 'Basic Info',
      groupOrder: 1,
      displayOrder: 3,
      inputType: 'text',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      maxLength: 3,
      placeholder: 'e.g. PH',
      helpText: 'ISO country code where the exchange is located',
    },
    timezone: {
      label: 'Timezone',
      group: 'Basic Info',
      groupOrder: 1,
      displayOrder: 4,
      inputType: 'text',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: false,
      placeholder: 'e.g. Asia/Manila',
    },
  },
  fieldGroups: ['Basic Info'],
};
