import type { EntityFieldDefaults } from './types';

export const feeTypeFieldConfig: EntityFieldDefaults = {
  fields: {
    code: {
      label: 'Fee Type Code',
      group: 'Basic Info',
      groupOrder: 1,
      displayOrder: 1,
      inputType: 'text',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      uniqueCheck: true,
      maxLength: 30,
      placeholder: 'e.g. TRUSTEE',
    },
    name: {
      label: 'Fee Type Name',
      group: 'Basic Info',
      groupOrder: 1,
      displayOrder: 2,
      inputType: 'text',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      placeholder: 'e.g. Trustee Fee',
    },
    description: {
      label: 'Description',
      group: 'Basic Info',
      groupOrder: 1,
      displayOrder: 3,
      inputType: 'textarea',
      required: false,
      visibleInTable: false,
      visibleInForm: true,
      sortable: false,
      placeholder: 'Description of the fee type',
    },
    calculation_method: {
      label: 'Calculation Method',
      group: 'Basic Info',
      groupOrder: 1,
      displayOrder: 4,
      inputType: 'select',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      selectOptionsSource: 'FIXED,PERCENTAGE,TIERED',
      helpText: 'How the fee is calculated',
    },
  },
  fieldGroups: ['Basic Info'],
};
