import type { EntityFieldDefaults } from './types';

export const feedRoutingFieldConfig: EntityFieldDefaults = {
  fields: {
    routing_id: {
      label: 'Routing ID',
      group: 'Routing Info',
      groupOrder: 1,
      displayOrder: 1,
      inputType: 'text',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      uniqueCheck: true,
    },
    security_segment: {
      label: 'Security Segment',
      group: 'Routing Info',
      groupOrder: 1,
      displayOrder: 2,
      inputType: 'select',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      selectOptionsSource: 'PH_BLUE_CHIP,PH_MID_CAP,PH_SMALL_CAP,FOREIGN_G10,FOREIGN_EM,FIXED_INCOME',
    },
    primary_source: {
      label: 'Primary Source',
      group: 'Routing Info',
      groupOrder: 1,
      displayOrder: 3,
      inputType: 'select',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: false,
      selectOptionsSource: 'DTCC,BLOOMBERG,REUTERS,PDTC,SWIFT',
    },
    secondary_source: {
      label: 'Secondary Source',
      group: 'Routing Info',
      groupOrder: 1,
      displayOrder: 4,
      inputType: 'select',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: false,
      selectOptionsSource: 'DTCC,BLOOMBERG,REUTERS,PDTC,SWIFT',
    },
    cost_tier: {
      label: 'Cost Tier',
      group: 'Routing Info',
      groupOrder: 1,
      displayOrder: 5,
      inputType: 'select',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      selectOptionsSource: 'BASELINE,PREMIUM',
    },
    active_flag: {
      label: 'Active',
      group: 'Routing Info',
      groupOrder: 1,
      displayOrder: 6,
      inputType: 'switch',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: false,
    },
  },
  fieldGroups: ['Routing Info'],
};
