import type { EntityFieldDefaults } from './types';

export const heldAwayAssetFieldConfig: EntityFieldDefaults = {
  fields: {
    portfolio_id: {
      label: 'Portfolio ID',
      group: 'Asset Details',
      groupOrder: 1,
      displayOrder: 1,
      inputType: 'text',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
    },
    asset_class: {
      label: 'Asset Class',
      group: 'Asset Details',
      groupOrder: 1,
      displayOrder: 2,
      inputType: 'text',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
    },
    description: {
      label: 'Description',
      group: 'Asset Details',
      groupOrder: 1,
      displayOrder: 3,
      inputType: 'text',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: false,
    },
    custodian: {
      label: 'Custodian',
      group: 'Location',
      groupOrder: 2,
      displayOrder: 4,
      inputType: 'text',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
    },
    location: {
      label: 'Location',
      group: 'Location',
      groupOrder: 2,
      displayOrder: 5,
      inputType: 'text',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: false,
    },
    market_value: {
      label: 'Market Value',
      group: 'Valuation',
      groupOrder: 3,
      displayOrder: 6,
      inputType: 'number',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
    },
    currency: {
      label: 'Currency',
      group: 'Valuation',
      groupOrder: 3,
      displayOrder: 7,
      inputType: 'text',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: false,
      placeholder: 'PHP',
    },
    as_of_date: {
      label: 'As Of Date',
      group: 'Valuation',
      groupOrder: 3,
      displayOrder: 8,
      inputType: 'date',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
    },
  },
  fieldGroups: ['Asset Details', 'Location', 'Valuation'],
};
