import type { EntityFieldDefaults } from './types';

export const legalEntityFieldConfig: EntityFieldDefaults = {
  fields: {
    entity_code: {
      label: 'Entity Code',
      group: 'Entity Info',
      groupOrder: 1,
      displayOrder: 1,
      inputType: 'text',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      uniqueCheck: true,
      maxLength: 20,
      placeholder: 'e.g. TRUST',
      helpText: 'Unique entity code (TRUST, IMA, CUST)',
    },
    entity_name: {
      label: 'Entity Name',
      group: 'Entity Info',
      groupOrder: 1,
      displayOrder: 2,
      inputType: 'text',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      placeholder: 'e.g. Trust Business',
    },
    regulator: {
      label: 'Regulator',
      group: 'Entity Info',
      groupOrder: 1,
      displayOrder: 3,
      inputType: 'select',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      selectOptionsSource: 'BSP,SEC',
    },
    license_ref: {
      label: 'License Reference',
      group: 'Entity Info',
      groupOrder: 1,
      displayOrder: 4,
      inputType: 'text',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: false,
      placeholder: 'e.g. TL-001',
    },
    base_currency: {
      label: 'Base Currency',
      group: 'Entity Info',
      groupOrder: 1,
      displayOrder: 5,
      inputType: 'text',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: false,
      maxLength: 3,
      placeholder: 'e.g. PHP',
    },
    data_segregation_scope: {
      label: 'Data Segregation',
      group: 'Entity Info',
      groupOrder: 1,
      displayOrder: 6,
      inputType: 'select',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: false,
      selectOptionsSource: 'HARD,SOFT',
      helpText: 'Hard = separate schema/DB; Soft = shared reference data',
    },
  },
  fieldGroups: ['Entity Info'],
};
