import type { EntityFieldDefaults } from './types';

export const marketCalendarFieldConfig: EntityFieldDefaults = {
  fields: {
    calendar_key: {
      label: 'Calendar Key',
      group: 'Calendar Info',
      groupOrder: 1,
      displayOrder: 1,
      inputType: 'select',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      selectOptionsSource: 'PH,US,HK,SG,PDEx,JP,UK',
      placeholder: 'e.g. PH',
      helpText: 'Market calendar identifier (e.g. PH for Philippines)',
    },
    date: {
      label: 'Date',
      group: 'Calendar Info',
      groupOrder: 1,
      displayOrder: 2,
      inputType: 'date',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
    },
    is_business_day: {
      label: 'Business Day',
      group: 'Calendar Info',
      groupOrder: 1,
      displayOrder: 3,
      inputType: 'switch',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: false,
    },
    is_settlement_day: {
      label: 'Settlement Day',
      group: 'Calendar Info',
      groupOrder: 1,
      displayOrder: 4,
      inputType: 'switch',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: false,
    },
    holiday_name: {
      label: 'Holiday Name',
      group: 'Calendar Info',
      groupOrder: 1,
      displayOrder: 5,
      inputType: 'text',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      placeholder: 'e.g. Araw ng Kagitingan',
    },
    source: {
      label: 'Source',
      group: 'Calendar Info',
      groupOrder: 1,
      displayOrder: 6,
      inputType: 'text',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: false,
      placeholder: 'e.g. BSP',
      helpText: 'Data source (BSP, PSE, Exchange website)',
    },
  },
  fieldGroups: ['Calendar Info'],
};
