import type { EntityFieldDefaults } from './types';

export const modelPortfolioFieldConfig: EntityFieldDefaults = {
  fields: {
    name: {
      label: 'Model Name',
      group: 'Basic Info',
      groupOrder: 1,
      displayOrder: 1,
      inputType: 'text',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      uniqueCheck: true,
      placeholder: 'e.g. Conservative Bond Model',
    },
    description: {
      label: 'Description',
      group: 'Basic Info',
      groupOrder: 1,
      displayOrder: 2,
      inputType: 'textarea',
      required: false,
      visibleInTable: false,
      visibleInForm: true,
      sortable: false,
    },
    allocations: {
      label: 'Target Allocations',
      group: 'Allocations',
      groupOrder: 2,
      displayOrder: 3,
      inputType: 'json',
      required: false,
      visibleInTable: false,
      visibleInForm: true,
      sortable: false,
      helpText: 'JSON array: [{asset_class, target_pct, min_pct, max_pct}]',
    },
    benchmark_id: {
      label: 'Benchmark ID',
      group: 'Basic Info',
      groupOrder: 1,
      displayOrder: 4,
      inputType: 'number',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: false,
    },
    is_active: {
      label: 'Active',
      group: 'Basic Info',
      groupOrder: 1,
      displayOrder: 5,
      inputType: 'switch',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
    },
  },
  fieldGroups: ['Basic Info', 'Allocations'],
};
