import type { EntityFieldDefaults } from './types';

export const peraAccountFieldConfig: EntityFieldDefaults = {
  fields: {
    contributor_id: {
      label: 'Contributor (Client ID)',
      group: 'Account Info',
      groupOrder: 1,
      displayOrder: 1,
      inputType: 'text',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
    },
    administrator: {
      label: 'PERA Administrator',
      group: 'Account Info',
      groupOrder: 1,
      displayOrder: 2,
      inputType: 'text',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
    },
    product_id: {
      label: 'Product ID',
      group: 'Account Info',
      groupOrder: 1,
      displayOrder: 3,
      inputType: 'number',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: false,
    },
    balance: {
      label: 'Balance',
      group: 'Financial',
      groupOrder: 2,
      displayOrder: 4,
      inputType: 'number',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
    },
    contribution_ytd: {
      label: 'Contribution YTD',
      group: 'Financial',
      groupOrder: 2,
      displayOrder: 5,
      inputType: 'number',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
    },
    max_contribution_annual: {
      label: 'Max Annual Contribution',
      group: 'Financial',
      groupOrder: 2,
      displayOrder: 6,
      inputType: 'number',
      required: false,
      visibleInTable: false,
      visibleInForm: true,
      sortable: false,
      helpText: 'BSP-mandated annual contribution cap',
    },
    tin: {
      label: 'TIN',
      group: 'Account Info',
      groupOrder: 1,
      displayOrder: 7,
      inputType: 'text',
      required: false,
      visibleInTable: false,
      visibleInForm: true,
      sortable: false,
      piiSensitive: true,
    },
    bsp_pera_id: {
      label: 'BSP PERA ID',
      group: 'Account Info',
      groupOrder: 1,
      displayOrder: 8,
      inputType: 'text',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: false,
      helpText: 'BSP PERA-Sys assigned ID',
    },
    pera_status: {
      label: 'Status',
      group: 'Account Info',
      groupOrder: 1,
      displayOrder: 9,
      inputType: 'select',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      selectOptions: [
        { value: 'ACTIVE', label: 'Active' },
        { value: 'SUSPENDED', label: 'Suspended' },
        { value: 'CLOSED', label: 'Closed' },
      ],
    },
  },
  fieldGroups: ['Account Info', 'Financial'],
};
