import type { EntityFieldDefaults } from './types';

export const portfolioFieldConfig: EntityFieldDefaults = {
  fields: {
    portfolio_id: {
      label: 'Portfolio ID',
      group: 'Basic Info',
      groupOrder: 1,
      displayOrder: 1,
      inputType: 'text',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      uniqueCheck: true,
      placeholder: 'e.g. PF-IMA-001',
      helpText: 'Unique portfolio identifier',
    },
    client_id: {
      label: 'Client',
      group: 'Basic Info',
      groupOrder: 1,
      displayOrder: 2,
      inputType: 'lookup',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      selectOptionsSource: 'clients',
      helpText: 'The client who owns this portfolio',
    },
    type: {
      label: 'Portfolio Type',
      group: 'Investment',
      groupOrder: 2,
      displayOrder: 3,
      inputType: 'select',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      selectOptionsSource: 'IMA_DIRECTED,IMA_DISCRETIONARY,PMT,UITF,PRE_NEED,EMPLOYEE_BENEFIT,ESCROW,AGENCY,SAFEKEEPING',
      helpText: 'Trust product type classification',
    },
    base_currency: {
      label: 'Base Currency',
      group: 'Investment',
      groupOrder: 2,
      displayOrder: 4,
      inputType: 'text',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      maxLength: 3,
      placeholder: 'e.g. PHP',
    },
    aum: {
      label: 'AUM',
      group: 'Investment',
      groupOrder: 2,
      displayOrder: 5,
      inputType: 'currency',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      editable: false,
      sortable: true,
      helpText: 'Assets Under Management (system-calculated)',
    },
    inception_date: {
      label: 'Inception Date',
      group: 'Status',
      groupOrder: 3,
      displayOrder: 6,
      inputType: 'date',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
    },
    portfolio_status: {
      label: 'Status',
      group: 'Status',
      groupOrder: 3,
      displayOrder: 7,
      inputType: 'select',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      selectOptionsSource: 'ACTIVE,SUSPENDED,CLOSED,PENDING_ACTIVATION',
    },
  },
  fieldGroups: ['Basic Info', 'Investment', 'Status'],
};
