import type { EntityFieldDefaults } from './types';

export const scheduledPlanFieldConfig: EntityFieldDefaults = {
  fields: {
    client_id: {
      label: 'Client ID',
      group: 'Plan Details',
      groupOrder: 1,
      displayOrder: 1,
      inputType: 'text',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
    },
    portfolio_id: {
      label: 'Portfolio ID',
      group: 'Plan Details',
      groupOrder: 1,
      displayOrder: 2,
      inputType: 'text',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
    },
    plan_type: {
      label: 'Plan Type',
      group: 'Plan Details',
      groupOrder: 1,
      displayOrder: 3,
      inputType: 'select',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      selectOptions: [
        { value: 'EIP', label: 'Easy Investment Plan (EIP)' },
        { value: 'ERP', label: 'Easy Redemption Plan (ERP)' },
      ],
    },
    amount: {
      label: 'Amount',
      group: 'Schedule',
      groupOrder: 2,
      displayOrder: 4,
      inputType: 'number',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
    },
    currency: {
      label: 'Currency',
      group: 'Schedule',
      groupOrder: 2,
      displayOrder: 5,
      inputType: 'text',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: false,
      placeholder: 'PHP',
    },
    frequency: {
      label: 'Frequency',
      group: 'Schedule',
      groupOrder: 2,
      displayOrder: 6,
      inputType: 'select',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: false,
      selectOptions: [
        { value: 'DAILY', label: 'Daily' },
        { value: 'WEEKLY', label: 'Weekly' },
        { value: 'BI_WEEKLY', label: 'Bi-Weekly' },
        { value: 'MONTHLY', label: 'Monthly' },
        { value: 'QUARTERLY', label: 'Quarterly' },
      ],
    },
    ca_sa_account: {
      label: 'CA/SA Account',
      group: 'Schedule',
      groupOrder: 2,
      displayOrder: 7,
      inputType: 'text',
      required: false,
      visibleInTable: false,
      visibleInForm: true,
      sortable: false,
      helpText: 'Current/Savings account for auto-debit/credit',
    },
    next_execution_date: {
      label: 'Next Execution',
      group: 'Schedule',
      groupOrder: 2,
      displayOrder: 8,
      inputType: 'date',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
    },
    scheduled_plan_status: {
      label: 'Status',
      group: 'Plan Details',
      groupOrder: 1,
      displayOrder: 9,
      inputType: 'select',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      selectOptions: [
        { value: 'ACTIVE', label: 'Active' },
        { value: 'PAUSED', label: 'Paused' },
        { value: 'CANCELLED', label: 'Cancelled' },
        { value: 'COMPLETED', label: 'Completed' },
      ],
    },
  },
  fieldGroups: ['Plan Details', 'Schedule'],
};
