import type { EntityFieldDefaults } from './types';

export const securityFieldConfig: EntityFieldDefaults = {
  fields: {
    isin: {
      label: 'ISIN',
      group: 'Identifiers',
      groupOrder: 1,
      displayOrder: 1,
      inputType: 'isin',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      uniqueCheck: true,
      maxLength: 12,
      placeholder: 'e.g. PHY0483F1004',
      helpText: 'International Securities Identification Number',
    },
    cusip: {
      label: 'CUSIP',
      group: 'Identifiers',
      groupOrder: 1,
      displayOrder: 2,
      inputType: 'text',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: false,
      maxLength: 9,
      placeholder: 'e.g. 037833100',
    },
    sedol: {
      label: 'SEDOL',
      group: 'Identifiers',
      groupOrder: 1,
      displayOrder: 3,
      inputType: 'text',
      required: false,
      visibleInTable: false,
      visibleInForm: true,
      sortable: false,
      maxLength: 7,
      placeholder: 'e.g. 2046251',
    },
    bloomberg_ticker: {
      label: 'Bloomberg Ticker',
      group: 'Identifiers',
      groupOrder: 1,
      displayOrder: 4,
      inputType: 'text',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      placeholder: 'e.g. SM PM Equity',
    },
    local_code: {
      label: 'Local Code',
      group: 'Identifiers',
      groupOrder: 1,
      displayOrder: 5,
      inputType: 'text',
      required: false,
      visibleInTable: false,
      visibleInForm: true,
      sortable: false,
      placeholder: 'e.g. SM',
      helpText: 'Local exchange ticker symbol',
    },
    name: {
      label: 'Security Name',
      group: 'Classification',
      groupOrder: 2,
      displayOrder: 6,
      inputType: 'text',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      placeholder: 'e.g. SM Investments Corporation',
    },
    asset_class: {
      label: 'Asset Class',
      group: 'Classification',
      groupOrder: 2,
      displayOrder: 7,
      inputType: 'select',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      selectOptionsSource: 'asset-classes',
      helpText: 'Primary asset classification',
    },
    sector: {
      label: 'Sector',
      group: 'Classification',
      groupOrder: 2,
      displayOrder: 8,
      inputType: 'text',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      placeholder: 'e.g. Financials',
    },
    exchange: {
      label: 'Exchange',
      group: 'Classification',
      groupOrder: 2,
      displayOrder: 9,
      inputType: 'text',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      placeholder: 'e.g. PSE',
    },
    currency: {
      label: 'Currency',
      group: 'Pricing',
      groupOrder: 3,
      displayOrder: 10,
      inputType: 'text',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      maxLength: 3,
      placeholder: 'e.g. PHP',
    },
    is_active: {
      label: 'Active',
      group: 'Status',
      groupOrder: 4,
      displayOrder: 11,
      inputType: 'switch',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
    },
  },
  fieldGroups: ['Identifiers', 'Classification', 'Pricing', 'Status'],
};
