import type { EntityFieldDefaults } from './types';

export const standingInstructionFieldConfig: EntityFieldDefaults = {
  fields: {
    account_id: {
      label: 'Account ID',
      group: 'Instruction Details',
      groupOrder: 1,
      displayOrder: 1,
      inputType: 'text',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
    },
    portfolio_id: {
      label: 'Portfolio ID',
      group: 'Instruction Details',
      groupOrder: 1,
      displayOrder: 2,
      inputType: 'text',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
    },
    instruction_type: {
      label: 'Instruction Type',
      group: 'Instruction Details',
      groupOrder: 1,
      displayOrder: 3,
      inputType: 'select',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      selectOptions: [
        { value: 'AUTO_ROLL', label: 'Auto Roll' },
        { value: 'AUTO_CREDIT', label: 'Auto Credit' },
        { value: 'AUTO_WITHDRAWAL', label: 'Auto Withdrawal' },
      ],
    },
    params: {
      label: 'Parameters',
      group: 'Configuration',
      groupOrder: 2,
      displayOrder: 4,
      inputType: 'json',
      required: false,
      visibleInTable: false,
      visibleInForm: true,
      sortable: false,
      helpText: 'JSON: {target_account, amount, frequency, etc.}',
    },
    is_active: {
      label: 'Active',
      group: 'Instruction Details',
      groupOrder: 1,
      displayOrder: 5,
      inputType: 'switch',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
    },
    next_execution_date: {
      label: 'Next Execution',
      group: 'Configuration',
      groupOrder: 2,
      displayOrder: 6,
      inputType: 'date',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
    },
  },
  fieldGroups: ['Instruction Details', 'Configuration'],
};
