import type { EntityFieldDefaults } from './types';

export const taxCodeFieldConfig: EntityFieldDefaults = {
  fields: {
    code: {
      label: 'Tax Code',
      group: 'Basic Info',
      groupOrder: 1,
      displayOrder: 1,
      inputType: 'text',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      uniqueCheck: true,
      maxLength: 20,
      placeholder: 'e.g. WHT-20',
    },
    name: {
      label: 'Tax Code Name',
      group: 'Basic Info',
      groupOrder: 1,
      displayOrder: 2,
      inputType: 'text',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      placeholder: 'e.g. Withholding Tax 20%',
    },
    rate: {
      label: 'Tax Rate',
      group: 'Rate',
      groupOrder: 2,
      displayOrder: 3,
      inputType: 'percentage',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      minValue: 0,
      maxValue: 100,
      helpText: 'Tax rate as a percentage',
    },
    type: {
      label: 'Tax Type',
      group: 'Basic Info',
      groupOrder: 1,
      displayOrder: 4,
      inputType: 'select',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      selectOptionsSource: 'WHT,FATCA,CRS',
      helpText: 'Classification of the tax type',
    },
    applicability: {
      label: 'Applicability',
      group: 'Rate',
      groupOrder: 2,
      displayOrder: 5,
      inputType: 'textarea',
      required: false,
      visibleInTable: false,
      visibleInForm: true,
      sortable: false,
      placeholder: 'Describe when this tax code applies',
    },
  },
  fieldGroups: ['Basic Info', 'Rate'],
};
