import type { EntityFieldDefaults } from './types';

export const userFieldConfig: EntityFieldDefaults = {
  fields: {
    username: {
      label: 'Username',
      group: 'Account',
      groupOrder: 1,
      displayOrder: 1,
      inputType: 'text',
      required: true,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      uniqueCheck: true,
      placeholder: 'e.g. jdcruz',
    },
    full_name: {
      label: 'Full Name',
      group: 'Account',
      groupOrder: 1,
      displayOrder: 2,
      inputType: 'text',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      placeholder: 'e.g. Juan Dela Cruz',
    },
    email: {
      label: 'Email',
      group: 'Account',
      groupOrder: 1,
      displayOrder: 3,
      inputType: 'email',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      uniqueCheck: true,
      placeholder: 'e.g. jdcruz@trustco.ph',
    },
    role: {
      label: 'Role',
      group: 'Assignment',
      groupOrder: 2,
      displayOrder: 4,
      inputType: 'select',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      selectOptionsSource: 'BO_MAKER,BO_CHECKER,BO_HEAD,RELATIONSHIP_MANAGER,SENIOR_RM,TRADER,SENIOR_TRADER,MO_MAKER,MO_CHECKER,FUND_ACCOUNTANT,COMPLIANCE_OFFICER,CCO,RISK_OFFICER,CRO,TRUST_BUSINESS_HEAD,SYSTEM_ADMIN',
      helpText: 'Primary system role assignment',
    },
    department: {
      label: 'Department',
      group: 'Assignment',
      groupOrder: 2,
      displayOrder: 5,
      inputType: 'text',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      placeholder: 'e.g. Trust Operations',
    },
    office: {
      label: 'Office',
      group: 'Assignment',
      groupOrder: 2,
      displayOrder: 6,
      inputType: 'select',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
      selectOptionsSource: 'FRONT_OFFICE,MIDDLE_OFFICE,BACK_OFFICE,COMPLIANCE,RISK,EXECUTIVE',
    },
    is_active: {
      label: 'Active',
      group: 'Status',
      groupOrder: 3,
      displayOrder: 7,
      inputType: 'switch',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: true,
    },
    mfa_enabled: {
      label: 'MFA Enabled',
      group: 'Status',
      groupOrder: 3,
      displayOrder: 8,
      inputType: 'switch',
      required: false,
      visibleInTable: true,
      visibleInForm: true,
      sortable: false,
      helpText: 'Whether multi-factor authentication is enabled',
    },
  },
  fieldGroups: ['Account', 'Assignment', 'Status'],
};
